name: Build the docker image

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build . -t dokho1984/transmission-daemon:latest
      - name: push
        run: |
          docker push dokho1984/transmission-daemon:latest